### PR TITLE
Track unsaved changes / prompts related to unsaved changes

### PR DESCRIPTION
**Pull request by dl471**
I tried to add a bit of extra functionality related to saving data. Tabs will now keep track of whether or not changes have been made to the files they are attached to and users will be notified if they are about to lose a file with unsaved data. Unfortunately I didn't commit frequently, so this pull request is a bit large. Sorry about that.

This is the full list of what I've changed:

- Addition of TabExtraInfo which tracks presence  ofunsaved changes and save path associated with file
- Visual indicator for unsaved changes
- Prompting when user attempts to close file with unsaved changes
- Prompting when user attempts to exit application with unsaved changes
- Addition of Save All button
- Modification of Save As to update filePath used for subsequent saves and SelectedTab.Text to match new name (previously functioned more like a Save Copy As function)
- Changed saveToolStripMenuItem_Click function to use TabExtraInfo.filePath as the existing provisions for save path seemed to get confused after opening/closing tabs

### CODE REVIEW

**Comment by CoderJoeW** [comment]
Looks very promising :D just waiting for the ci to complete

In the future I would appreciate if you modified the `ChangeLog.md` with changes as you do them it just makes it a lot easier instead of me having to go back and review all the changes and adding them to the changelog

**Comment by CoderJoeW** [comment]
Build fails error returned by travis `Form1.cs(368,51): error CS0246: The type or namespace name 'TabExtraInfo' could not be found (are you missing a using directive or an assembly reference?) [/home/travis/build/flaminggenius/CSVAnalyzerPro/CSV Analyzer Pro/CSV Analyzer Pro/CSV Analyzer Pro.csproj]
Form1.cs(385,50): error CS0246: The type or namespace name 'TabExtraInfo' could not be found (are you missing a using directive or an assembly reference?) [/home/travis/build/flaminggenius/CSVAnalyzerPro/CSV Analyzer Pro/CSV Analyzer Pro/CSV Analyzer Pro.csproj]
Form1.cs(35,14): error CS0246: The type or namespace name 'TabExtraInfo' could not be found (are you missing a using directive or an assembly reference?) [/home/travis/build/flaminggenius/CSVAnalyzerPro/CSV Analyzer Pro/CSV Analyzer Pro/CSV Analyzer Pro.csproj]`

**Comment by dl471** [comment]
Ah, the problem with Travis seemed to be a .csproj thing. I think that's it working now?

I'll keep the ChangeLog in mind for the future.

**Comment by CoderJoeW** [comment]
Thank you!!!

**Pull request merged**
