### PR TITLE
Alterations to CheckUpdate

### PR DESCRIPTION
**Pull request by dl471**
When I try to open the program it seems to hang a little with no feedback. The lack of feedback seems to have been a problem with the UI and processing logic sharing a thread and blocking each other, meaning the UI window never got a chance to draw itself until the checking was already over. The hanging appears to be dependent on how long it takes the user to connect to the update server and get a response, with the program silently failing if the connection times out or the server cannot be reached.

I tried to improve on these issues by changing the threading used in CheckUpdate, adding an extra step to the progress bar showing the attempt to connect to the update server and adding an exception handler for if the connection should fail for any reason.

### CODE REVIEW

**Comment by CoderJoeW** [comment]
Why are we exiting the application when the connection fails?

Since it's not required that the user be connected to the internet and if their offline the application with exit shouldn't we just warn the user that their offline and that we couldn't check for an update?

**Comment by dl471** [comment]
I assumed based on the existence of the InvalidLicense stuff that you didn't want that. I can definitely make it a simple warning and have the program proceed as usual if that's what you prefer though.

**Comment by CoderJoeW** [comment]
It would be I was planning to do that but never got around to it :)

**Comment by dl471** [comment]
Hmm. Are you still planning to add it later?

**Comment by CoderJoeW** [comment]
It can be added now I'm working on the spreadsheet switch (I created a separate branch for it) if you would like to help out with that there's a crash when clicking then file button once I get that straightened out we will have a working prototype capable of handling excel files along with csv files plus a lot more data manipulation controls

Once that's done I plan to add a better licensing system and selling the software as plans all contributors are welcome to participate in a rev-share agreement

**Comment by dl471** [comment]
A bit late but I changed it so that things just proceed as normal if the server can't be reached. I'd mostly like to get the stuff related to checking if the server can be reached and the progress bar in and that's a prerequisite for it. I'll start working on the file menu tomorrow.

**Comment by CoderJoeW** [comment]
Thank you!! I will upload my changes tonight.

**Pull request merged**
